### ISSUE TITLE
Requesting account for Miguel (iBook vendor)

### ISSUE THREAD

**Issue by lwtchu** [openstax/bit#279]
# Description
Can we get customer support level access to the errata tool for Miguel Garcia. `m.garcia.g@me.com` 

# Acceptance Criteria
He should be able to look at reports, filter them and be able to download any attachments on the issues. Let me know if there are any issues setting him up.

**Comment by mwharrison** [comment]
@lwtchu 
In order to give access to someone, they must have logged into the website before. I am not finding an account for him. Please ask him to login.

After he does - you have the power to give him the access. :)

You can go here to find his account: https://openstax.org/admin/users/?q=m.garcia.g@me.com
Then check the box shown in the screenshot below.

![screen shot 2019-03-05 at 12 05 06 pm](https://user-images.githubusercontent.com/3905516/53826734-00c65c00-3f3f-11e9-800d-0cf3a0492e3e.png)

**Comment by lwtchu** [comment]
:O

**Comment by lwtchu** [comment]
I'm going to close this. I was not aware of this powaaaa

**Comment by lwtchu** [comment]
I gave Miguel `S-Miguel.Garcia-gonz@lwtech.edu` Content Development Intern level access. And he's getting the following errors. Is there anythign else I'm missing? Thanks in advance :sob: @mwharrison 
![image2](https://user-images.githubusercontent.com/11299125/53985173-93eac780-40e0-11e9-8993-868f3286935d.jpeg)
![image1](https://user-images.githubusercontent.com/11299125/53985178-96e5b800-40e0-11e9-88d8-69ede288ec68.jpeg)

**Comment by mwharrison** [comment]
@lwtchu - sorry, there is one more step for accessing Errata.

You have to go into the Django admin and make the user a staff.
That can be done here: https://openstax.org/django-admin/auth/user/229905/change/?_changelist_filters=q%3DMiguel%2BGarcia

I've gone ahead and updated Miguel, so he should be good to go!
