### ISSUE TITLE
Book cover image file type is inconsistent

### ISSUE THREAD

**Issue by TomWoodward** [openstax/bit#45]
# Scenario 
when loading data from https://openstax.org/api/v2/pages/?type=books.Book&limit=250&fields=cover_url,description,title,cnx_id the cover images are somtimes svg, sometimes png, and image sizes are not consistent.

when using the cover images as og:image content (for facebook, slack, etc previews) the svg type is not valid. facebook reports ```Unsupported Image File Extension
Provided og:image URL, https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/elementary-algebra.svg does not have a supported extension.```

it would be nice if 
1) they were all png or other supported format
2) they had consistent size (or at least consistent aspect ratio)

# Environment

**Comment by mwharrison** [comment]
@TomWoodward - For Facebook sharing, you'll want to use the `search_description` and `sep_title` like so: https://openstax.org/api/v2/pages/?type=books.Book&limit=250&fields=cover_url,description,title,cnx_id,search_description,seo_title.

For the image, there is a new field getting released soon, called the `promote_image` which will be used specifically for social sharing (so we'll make sure it's a PNG).

Hopefully this helps - let me know if you need anything else!

**Comment by TomWoodward** [comment]
@mwharrison the `search_description` and `seo_title` fields are both empty for all books, are those new fields? when could we expect them to be populated?

**Comment by allisonhowell** [comment]
@TomWoodward I've had my intern input all content.

**Comment by TomWoodward** [comment]
@mwharrison  can we add the `promote_image` field to the api responses?

**Comment by Malar-Natarajan** [comment]
go into the CMS and make sure the “promote” tab for a page has an image attached: https://cms-qa.openstax.org/admin/pages/29/edit/#tab-promote then visit the api for the page https://cms-qa.openstax.org/api/pages/openstax-homepage and verify the image is there under `promote_image`.
the homepage already has an image, so you can just verify in the API (edited)
oh, I guess for completeness - making sure `seo_title` and `search_description` are there is good - since that’s on the card.
those are both under `meta`

**Comment by Malar-Natarajan** [comment]
Verified in QA
